name: Tests and Build exe
on: push
env:
  GITHUB_ACTIONS_RUNNER: runner
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - run: pip install nox==2019.11.9
      - run: pip install poetry==1.0.5
      - run: nox

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          pip install poetry==1.0.5
          poetry install
          pip install -e .
      - name: Build with pyinstaller
        run: python -m PyInstaller.__main__ cli.py --name "dm" --onefile
      - uses: actions/upload-artifact@master
        with:
          name: Windows
          path: dist/dm.exe
